trigger:
  - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: PublishPackages
    steps:
      - template: azure-template.yml
      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: dotnet pack .\EFCore.PG.sln -o temp/publish
        displayName: "Pack packages"
      - task: PowerShell@2
        inputs:
          targetType: "inline"
          script: dotnet nuget push --skip-duplicate --source "https://pkgs.dev.azure.com/InProStudio/_packaging/inpro-shared/nuget/v3/index.json" --api-key az temp/publish/
        displayName: "Publish packages"